name: Test

on:
  pull_request: {}
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
      id: get-github-apps
      with:
        client-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}
        owner: nnsnodnb
        repositories: gs-reminder

    - name: Setup Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: "3.15"

    - name: Install required-version defined in pyproject.toml
      uses: astral-sh/setup-uv@1c37ad07a6a961277cf70c0d37d6f313000f5884 # v10.3.0
      with:
        python-version: "3.14"
        enable-cache: 'true'

    - name: Send Test
      env:
        GITHUB_TOKEN: ${{ steps.get-github-apps.outputs.token }}
        SLACK_URL: ${{ secrets.SLACK_URL }}
        REPOSITORY: ${{ github.repository }}
      run: |
        uv run python -m gs_reminder -r "${REPOSITORY}" -u ./examples/username.json

  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13", "3.14" ]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install required-version defined in pyproject.toml
        uses: astral-sh/setup-uv@1c37ad07a6a961277cf70c0d37d6f313000f5884 # v10.3.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: 'true'

      - name: Run Tests
        run: uv run python -m pytest -v tests
