name: Test

on:
  pull_request: {}
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

    - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
      id: get-github-apps
      with:
        client-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}
        owner: nnsnodnb
        repositories: gs-reminder

    - name: Setup Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: "3.14"

    - name: Install required-version defined in pyproject.toml
      uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
      with:
        python-version: "3.14"
        enable-cache: 'true'

    - name: Send Test
      env:
        GITHUB_TOKEN: ${{ steps.get-github-apps.outputs.token }}
        SLACK_URL: ${{ secrets.SLACK_URL }}
        REPOSITORY: ${{ github.repository }}
      run: |
        uv run python -m gs_reminder -r "${REPOSITORY}" -u ./examples/username.json

  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13", "3.14" ]

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803  # v6.1.0

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install required-version defined in pyproject.toml
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: 'true'

      - name: Run Tests
        run: uv run python -m pytest -v tests
